### ISSUE TITLE
[REQUEST] Filter out folders from the folder_brief_live

### ISSUE THREAD

**Issue by Luca-s-Works** [xpgo/obsidian-folder-note-plugin#10]
Hello there,

if possible, **can we have a keyword to specify the target type of cards to be generated within a ccard block of type folder_brief_live?**
I'd like to only show cards in my folder_brief_live about notes, not folders. I believe this could be a useful feature of general use. The passed value can be notes only, folder only or both. I've tried to look for this feature in the documentation or in the previously opened issues, but I haven't found anything about it. If I've missed, I apologize.

Also, allow me to include my sincere gratitude at the end of this post. Thanks a lot for all the effort and work you're doing with this plug-in. It's pretty awesome and really fill a lacune of Obsidian, IMHO. I hope to be absorbed and integrated officially in the Obsidian program.

**Comment by xpgo** [comment]
it already has a keyword for this feature, please see: [noteOnly key](https://github.com/xpgo/obsidian-folder-note-plugin/blob/main/doc/ccard-syntax.md#noteonly-false), make sure you have updated the plugin to v0.7.1. In the future, I am thinking of adding filter keyword based on regex and sorting keyword.

Thanks, I'd be glad if it could be integrated officially, because:
1. I don't have much time to maintain the plugin
2. there are many limitations in the obsidian's plugin API, I have to use many tricks to implement some features.

**Comment by Luca-s-Works** [comment]
Hello, Thanks again for your reply. I'm sorry for posting a request for something already implemented.
I've seen the documentation now includes also all the latest features listed in the various changelog, like the new "strip" card style. Awesome!

I proceed closing the issue.
